#
#
server:
  port: 8081
spring:
  application:
    name: customer-service
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservcies
management:
  security:
    enabled: false
  endpoints.web.exposure.include: '*'
logging:
  level.me.jhwang: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka